### ISSUE TITLE
No Certificate Password Output Found in the NiFi-output.tf File

### ISSUE THREAD

**Issue by snyderdb** [chadgeary/nifi#11]
There isn't a Certificate Password output in the Nifi-Output.tf file.

How can one obtain a password for the ceritficate?

**Comment by chadgeary** [comment]
https://github.com/chadgeary/nifi/blob/master/zks-on-ec2/nifi.tfvars#L9

**Comment by snyderdb** [comment]
Thanks!Sent from my iPhoneOn Jan 4, 2023, at 4:48 PM, Chad ***@***.***> wrote:﻿
https://github.com/chadgeary/nifi/blob/master/zks-on-ec2/nifi.tfvars#L9
