### ISSUE TITLE
Unable to Access the NLB UI After Successful Execution of Terraform

### ISSUE THREAD

**Issue by snyderdb** [chadgeary/nifi#12]
**Terraform apply was successful.**

Apply complete! Resources: 176 added, 0 changed, 0 destroyed.

**And, I obtained the following outputs:**

Outputs:

tf-nifi-output = <<EOT

# NiFi can take 15+ minutes to initialize a cluster, please be patient.
# State Manager Association will show Status: Complete, then
# NLB Target Group will show Status: healthy

# State Manager Association (Zookeepers)
https://console.aws.amazon.com/systems-manager/state-manager/59329fa9-8792-451c-bf16-f6a2d5457d89/executionhistory

# NLB Target Group (Zookeepers)
https://console.aws.amazon.com/ec2/v2/home?region=us-east-1#TargetGroup:targetGroupArn=arn:aws:elasticloadbalancing:us-east-1:826708293712:targetgroup/nifi-mgmt-2170-1gj84/5ef82290f0e45160

# Cloudwatch Logs
https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Fec2$252Fnifi_1gj84

# Admin Certificate
https://s3.console.aws.amazon.com/s3/object/nifi-bucket-1gj84?region=us-east-1&prefix=nifi/certificates/admin/keystore.p12

# NLB WebUI
https://nifi-node-nlb-1gj84-88562be6c981c467.elb.us-east-1.amazonaws.com:2170/nifi

# NLB Service Ports
nifi-node-nlb-1gj84-88562be6c981c467.elb.us-east-1.amazonaws.com

# Instance IDs in Cluster
AWS_PROFILE=default aws ec2 describe-instances --region us-east-1 --query 'Reservations[].Instances[*].[InstanceId, LaunchTime, [Tags[?Key==`Name`].Value][0][0]]' --filters Name=tag:Cluster,Values=nifi_1gj84 Name=instance-state-name,Values=pending,running --output text

# Connecting via SSM, append an instance-id from above command
AWS_PROFILE=default aws ssm start-session --region us-east-1 --target

# Re-run Ansible (SSM Associations)
# Zookeepers
AWS_PROFILE=default aws ssm start-associations-once --region us-east-1 --association-ids 59329fa9-8792-451c-bf16-f6a2d5457d89
# Nodes
AWS_PROFILE=default aws ssm start-associations-once --region us-east-1 --association-ids 28ffb38f-571e-4ecc-86cc-f914ea0d134c

**I was able to successfully import the cert into my firefox and chrome.**

**I then tried to hit** 
https://nifi-node-nlb-1gj84-88562be6c981c467.elb.us-east-1.amazonaws.com:2170/nifi

**It error'd out after a couple of minutes.**

**I then looked at Route 53, saw that Terrafolrm created a domain named "nifi1gj84.internal.**

**I ran the following command on the ubuntu client:  host -t NS nifi1gj84.internal**
**Host nifi1gj84.internal not found: 3(NXDOMAIN) so clearly the host, nifi1gj84.internal can't be found.**

Any guidance/suggestion re: why the host nifigj84.internal can't be found?

**Comment by chadgeary** [comment]
Q1:
> I then tried to hit https://nifi-node-nlb-1gj84-88562be6c981c467.elb.us-east-1.amazonaws.com:2170/nifi
It error'd out after a couple of minutes.

In the terraform output you pasted, this is mentioned:
```
State Manager Association will show Status: Complete, then
NLB Target Group will show Status: healthy
```
Are both of these true?

Q2:
> why the host nifigj84.internal can't be found?

That is a route53 internal domain, it isn't public.

**Comment by snyderdb** [comment]
State Manager Association:


NLB Target Group:


So, yes, both of these are true.
Gotcha on the route 53 private hosted zone and I understand that it is only accessible from within the VPC that it is associated    with.
Just don't understand why I can hit it.
Thanks so much for your prompt reply!
VR,
Dave
P.S. I am truly not trying to be a pain and I appreciate your help.
    On Sunday, January 8, 2023 at 02:49:01 PM UTC, Chad ***@***.***> wrote:  
 
 


Q1:


I then tried to hit https://nifi-node-nlb-1gj84-88562be6c981c467.elb.us-east-1.amazonaws.com:2170/nifi
It error'd out after a couple of minutes.


In the terraform output you pasted, this is mentioned:
State Manager Association will show Status: Complete, then
NLB Target Group will show Status: healthy

Are both of these true?

Q2:


why the host nifigj84.internal can't be found?


That is a route53 internal domain, it isn't public.

**Comment by snyderdb** [comment]
On Sunday, January 8, 2023 at 03:01:19 PM UTC, David Snyder ***@***.***> wrote:  
 
  State Manager Association:


NLB Target Group:


So, yes, both of these are true.
Gotcha on the route 53 private hosted zone and I understand that it is only accessible from within the VPC that it is associated    with.
Just don't understand why I can hit it.
Thanks so much for your prompt reply!
VR,
Dave
P.S. I am truly not trying to be a pain and I appreciate your help.
    On Sunday, January 8, 2023 at 02:49:01 PM UTC, Chad ***@***.***> wrote:  
 
 


Q1:


I then tried to hit https://nifi-node-nlb-1gj84-88562be6c981c467.elb.us-east-1.amazonaws.com:2170/nifi
It error'd out after a couple of minutes.


In the terraform output you pasted, this is mentioned:
State Manager Association will show Status: Complete, then
NLB Target Group will show Status: healthy

Are both of these true?

Q2:


why the host nifigj84.internal can't be found?


That is a route53 internal domain, it isn't public.

**Comment by snyderdb** [comment]
FYI, I ran all of this in clients created in virtual box.  I decided to run all of this from an ubuntu client from my aws account.
Perhaps there is something causing an issue stemming from the virtual box environment.
VR,
Dave


    On Sunday, January 8, 2023 at 10:31:37 AM EST, David Snyder ***@***.***> wrote:  
 
  


    On Sunday, January 8, 2023 at 03:01:19 PM UTC, David Snyder ***@***.***> wrote:  
 
  State Manager Association:


NLB Target Group:


So, yes, both of these are true.
Gotcha on the route 53 private hosted zone and I understand that it is only accessible from within the VPC that it is associated    with.
Just don't understand why I can hit it.
Thanks so much for your prompt reply!
VR,
Dave
P.S. I am truly not trying to be a pain and I appreciate your help.
    On Sunday, January 8, 2023 at 02:49:01 PM UTC, Chad ***@***.***> wrote:  
 
 


Q1:


I then tried to hit https://nifi-node-nlb-1gj84-88562be6c981c467.elb.us-east-1.amazonaws.com:2170/nifi
It error'd out after a couple of minutes.


In the terraform output you pasted, this is mentioned:
State Manager Association will show Status: Complete, then
NLB Target Group will show Status: healthy

Are both of these true?

Q2:


why the host nifigj84.internal can't be found?


That is a route53 internal domain, it isn't public.

**Comment by chadgeary** [comment]
Has the `mgmt_cidr` var been set to the public ip of the client browser? see: 
https://github.com/chadgeary/nifi/blob/master/zks-on-ec2/nifi.tfvars#L16-L17

If it has, there are two options:
1. Temporary set mgmt_cidr to `0.0.0.0./0` - this would allow world access to the nifi nlb, or
2. Use `aws ssm start-session` to port forward 2170 to the client machine and browse to https://localhost:2170/nifi , e.g.:
```
# replace $INSTANCE_ID with a nifi ec2 instance id
aws ssm start-session --target $INSTANCE_ID \
    --document-name AWS-StartPortForwardingSession \
    --parameters '{"portNumber":["2170"],"localPortNumber":["2170"]}'```

**Comment by snyderdb** [comment]
This is really awesome Chad!  Thanks for your help!  I'm going to set the mgmt_cidr to 0.0.0.0/0 and see if this allows me to hit it successfully.

Really appreciate your input Chad.
I'll let u know how this goes...
    On Sunday, January 8, 2023 at 02:03:44 PM EST, Chad ***@***.***> wrote:  
 
 


Has the mgmt_cidr var been set to the public ip of the client browser? see:
https://github.com/chadgeary/nifi/blob/master/zks-on-ec2/nifi.tfvars#L16-L17

If it has, there are two options:
   
   - Temporary set mgmt_cidr to 0.0.0.0./0 - this would allow world access to the nifi nlb, or
   - Use aws ssm start-session to port forward 2170 to the client machine and browse to https://localhost:2170/nifi , e.g.:
# replace $INSTANCE_ID with a nifi ec2 instance id
aws ssm start-session --target $INSTANCE_ID \
    --document-name AWS-StartPortForwardingSession \
    --parameters '{"portNumber":["2170"],"localPortNumber":["2170"]}'```

**Comment by snyderdb** [comment]
Using 0.0.0.0./0 for mgmt cidr worked.
Thanks Chad!  Thanks for all of your help. Again, nice work!
    On Sunday, January 8, 2023 at 02:17:08 PM EST, David Snyder ***@***.***> wrote:  
 
  This is really awesome Chad!  Thanks for your help!  I'm going to set the mgmt_cidr to 0.0.0.0/0 and see if this allows me to hit it successfully.

Really appreciate your input Chad.
I'll let u know how this goes...
    On Sunday, January 8, 2023 at 02:03:44 PM EST, Chad ***@***.***> wrote:  
 
 


Has the mgmt_cidr var been set to the public ip of the client browser? see:
https://github.com/chadgeary/nifi/blob/master/zks-on-ec2/nifi.tfvars#L16-L17

If it has, there are two options:
   
   - Temporary set mgmt_cidr to 0.0.0.0./0 - this would allow world access to the nifi nlb, or
   - Use aws ssm start-session to port forward 2170 to the client machine and browse to https://localhost:2170/nifi , e.g.:
# replace $INSTANCE_ID with a nifi ec2 instance id
aws ssm start-session --target $INSTANCE_ID \
    --document-name AWS-StartPortForwardingSession \
    --parameters '{"portNumber":["2170"],"localPortNumber":["2170"]}'```

**Comment by chadgeary** [comment]
glad it worked out
