### ISSUE TITLE
Received the following errors when running terraform apply

### ISSUE THREAD

**Issue by snyderdb** [chadgeary/nifi#8]
dave@nifiubuntu:~/nifi/zks-on-ec2$ terraform apply "nifi.tfplan"
random_string.tf-nifi-random: Creating...
random_string.tf-nifi-random: Creation complete after 0s [id=3bcb9]
aws_iam_role.tf-nifi-instance-iam-role: Creating...
aws_iam_role.tf-nifi-autoscale-snsrole: Creating...
aws_iam_role.tf-nifi-iam-role-lambda-scaledown: Creating...
aws_ssm_document.tf-nifi-ssmdoc-scaledown: Creating...
aws_ssm_document.tf-nifi-ssm-playbook-doc: Creating...
aws_vpc_dhcp_options.tf-nifi-dhcp-opts: Creating...
aws_iam_role.tf-nifi-iam-role-lambda-health: Creating...
aws_cloudwatch_event_rule.tf-nifi-cloudwatch-event-rule-health: Creating...
aws_iam_role.tf-nifi-iam-role-lambda-certs: Creating...
aws_iam_role.tf-nifi-iam-role-lambda-getnifi: Creating...
aws_cloudwatch_event_rule.tf-nifi-cloudwatch-event-rule-health: Creation complete after 0s [id=nifi-event-rule-health-3bcb9]
aws_iam_service_linked_role.tf-nifi-autoscale-slr: Creating...
aws_vpc_dhcp_options.tf-nifi-dhcp-opts: Creation complete after 0s [id=dopt-0d3949796f4749c68]
aws_iam_service_linked_role.tf-nifi-autoscale-slr: Creation complete after 0s [id=arn:aws:iam::826708293712:role/aws-service-role/autoscaling.amazonaws.com/AWSServiceRoleForAutoScaling_nifi3bcb9]
aws_s3_bucket.tf-nifi-bucket: Creating...
aws_ssm_document.tf-nifi-ssmdoc-scaledown: Creation complete after 0s [id=nifi-ssmdoc-scaledown-3bcb9]
aws_ssm_document.tf-nifi-ssm-playbook-doc: Creation complete after 0s [id=nifi-ssm-playbook-doc-3bcb9]
aws_iam_role.tf-nifi-iam-role-lambda-certs: Creation complete after 1s [id=nifi-iam-role-lambda-certs-3bcb9]
aws_iam_role.tf-nifi-iam-role-lambda-scaledown: Creation complete after 1s [id=nifi-iam-role-lambda-scaledown-3bcb9]
aws_iam_role.tf-nifi-autoscale-snsrole: Creation complete after 1s [id=nifi-autoscale-sns-role-3bcb9]
aws_iam_role.tf-nifi-instance-iam-role: Creation complete after 1s [id=nifi-instance-role-3bcb9]
aws_iam_role.tf-nifi-iam-role-lambda-health: Creation complete after 1s [id=nifi-iam-role-lambda-health-3bcb9]
aws_iam_role.tf-nifi-iam-role-lambda-getnifi: Creation complete after 1s [id=nifi-iam-role-lambda-getnifi-3bcb9]
data.aws_iam_policy_document.tf-nifi-bucket: Reading...
data.aws_iam_policy_document.tf-nifi-bucket: Read complete after 0s [id=676879418]
aws_iam_instance_profile.tf-nifi-instance-profile: Creating...
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-certs-1: Creating...
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-certs-2: Creating...
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-1: Creating...
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-2: Creating...
aws_iam_role_policy_attachment.tf-nifi-iam-attach-ssm: Creating...
aws_iam_role_policy_attachment.tf-nifi-iam-attach-health-lambda-1: Creating...
aws_iam_role_policy_attachment.tf-nifi-iam-attach-health-lambda-2: Creating...
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-getnifi-2: Creating...
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-certs-1: Creation complete after 0s [id=nifi-iam-role-lambda-certs-3bcb9-20221230151318341500000002]
aws_iam_role_policy_attachment.tf-nifi-iam-attach-ssm: Creation complete after 0s [id=nifi-instance-role-3bcb9-20221230151318340800000001]
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-certs-2: Creation complete after 1s [id=nifi-iam-role-lambda-certs-3bcb9-20221230151318342900000003]
aws_iam_role_policy_attachment.tf-nifi-iam-attach-health-lambda-1: Creation complete after 1s [id=nifi-iam-role-lambda-health-3bcb9-20221230151318415500000005]
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-getnifi-1: Creating...
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-2: Creation complete after 1s [id=nifi-iam-role-lambda-scaledown-3bcb9-20221230151318421900000006]
aws_iam_role_policy_attachment.tf-nifi-iam-attach-health-lambda-2: Creation complete after 1s [id=nifi-iam-role-lambda-health-3bcb9-20221230151318464700000008]
aws_iam_instance_profile.tf-nifi-instance-profile: Creation complete after 1s [id=nifi-instance-profile-3bcb9]
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-getnifi-2: Creation complete after 1s [id=nifi-iam-role-lambda-getnifi-3bcb9-20221230151318443000000007]
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-1: Creation complete after 1s [id=nifi-iam-role-lambda-scaledown-3bcb9-20221230151318390100000004]
aws_s3_bucket.tf-nifi-bucket: Creation complete after 2s [id=nifi-bucket-3bcb9]
aws_iam_role_policy_attachment.tf-nifi-iam-attach-lambda-getnifi-1: Creation complete after 0s [id=nifi-iam-role-lambda-getnifi-3bcb9-20221230151318766100000009]
aws_s3_bucket_public_access_block.tf-nifi-bucket: Creating...
aws_s3_bucket_versioning.tf-nifi-bucket: Creating...
aws_s3_bucket_acl.tf-nifi-bucket: Creating...
aws_s3_bucket_policy.tf-nifi-bucket: Creating...
aws_s3_bucket_acl.tf-nifi-bucket: Creation complete after 0s [id=nifi-bucket-3bcb9,private]
aws_s3_bucket_public_access_block.tf-nifi-bucket: Creation complete after 1s [id=nifi-bucket-3bcb9]
aws_s3_bucket_versioning.tf-nifi-bucket: Creation complete after 2s [id=nifi-bucket-3bcb9]
aws_s3_bucket_policy.tf-nifi-bucket: Creation complete after 8s [id=nifi-bucket-3bcb9]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_kms_key.tf-nifi-kmscmk-lambda to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name"
│ has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_kms_key.tf-nifi-kmscmk-s3 to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name"
│ has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_eip.tf-nifi-ng-eip2 to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name" has
│ appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_kms_key.tf-nifi-kmscmk-sns to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name"
│ has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_eip.tf-nifi-ng-eip1 to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name" has
│ appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_kms_key.tf-nifi-kmscmk-ec2 to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name"
│ has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_kms_key.tf-nifi-kmscmk-cloudwatch to include new values learned so far during
│ apply, provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element
│ "Name" has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_key_pair.tf-nifi-instance-key to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name"
│ has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_kms_key.tf-nifi-kmscmk-ssm to include new values learned so far during apply,
│ provider "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name"
│ has appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_eip.tf-nifi-ng-eip3 to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name" has
│ appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for aws_vpc.tf-nifi-vpc to include new values learned so far during apply, provider
│ "registry.terraform.io/hashicorp/aws" produced an invalid new value for .tags_all: new element "Name" has
│ appeared.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

**Comment by chadgeary** [comment]
Hey @snyderdb - this is a popular bug in the AWS terraform provider.
https://github.com/hashicorp/terraform-provider-aws/issues/19583

Have you tried running `terraform apply` again?

**Comment by snyderdb** [comment]
No but I will!  Again great project!  Thanks for making this available Chad!Sent from my iPhoneOn Dec 30, 2022, at 11:42 AM, Chad ***@***.***> wrote:﻿
Hey @snyderdb - this is a popular bug in the AWS terraform provider.
hashicorp/terraform-provider-aws#19583
Have you tried running terraform apply again?

**Comment by snyderdb** [comment]
Hello Chad -
I attempted to run your code using Terraform version 1.3.6, a version that was in use in 7/2022.
I then applied the terraform scripts and obtained the same error as previously indicated.
If by chance you have a chance to look into this, I would love to hear if you have any quidance/suggestions for working through this...
VR,
Dave
    On Friday, December 30, 2022 at 11:51:55 AM EST, David Snyder ***@***.***> wrote:  
 
 No but I will!  Again great project!  Thanks for making this available Chad!

Sent from my iPhone

On Dec 30, 2022, at 11:42 AM, Chad ***@***.***> wrote:



﻿


Hey @snyderdb - this is a popular bug in the AWS terraform provider.
hashicorp/terraform-provider-aws#19583

Have you tried running terraform apply again?

**Comment by chadgeary** [comment]
You can try commenting out the tags section of the provider @ https://github.com/chadgeary/nifi/blob/master/zks-on-ec2/nifi-generic.tf#L122-L128

current:
```
provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
  default_tags {
    tags = var.aws_default_tags
  }
}
```

commented:
```
provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
#  default_tags {
#    tags = var.aws_default_tags
#  }
}
```

**Comment by snyderdb** [comment]
Thanks Chad!!Sent from my iPhoneOn Jan 2, 2023, at 10:38 AM, Chad ***@***.***> wrote:﻿
You can try commenting out the tags section of the provider @ https://github.com/chadgeary/nifi/blob/master/zks-on-ec2/nifi-generic.tf#L122-L128
current:
provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
  default_tags {
    tags = var.aws_default_tags
  }
}

commented:
provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
#  default_tags {
#    tags = var.aws_default_tags
#  }
}

**Comment by snyderdb** [comment]
Hello and good am Chad -
This did the trick, the terraform scrips executed w/out a hitch.
Thanks again Chad. 
I hope you don't mind some additional questions...
VR,
Dave
    On Monday, January 2, 2023 at 10:38:33 AM EST, Chad ***@***.***> wrote:  
 
 


You can try commenting out the tags section of the provider @ https://github.com/chadgeary/nifi/blob/master/zks-on-ec2/nifi-generic.tf#L122-L128

current:
provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
  default_tags {
    tags = var.aws_default_tags
  }
}

commented:
provider "aws" {
  region  = var.aws_region
  profile = var.aws_profile
#  default_tags {
#    tags = var.aws_default_tags
#  }
}
